### ISSUE TITLE
Switch Kafka UIs from Trifecta to provectus/kafka-ui

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-services#76]
We currently use [Trifecta](https://github.com/ldaniels528/trifecta#trifecta-ui) to check on Kafka queues, but this is not that widely used. We can switch to [akhq](https://akhq.io/) which seems to be more widely used and well supported.

```yaml
version: '3.7'
services:
  akhq:
    image: tchiotludo/akhq
    ports:
      - "58080:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            fc:
              properties:
                bootstrap.servers: "192.168.45.34:9094"
          security:
            default-group: reader
```
