### ISSUE TITLE
Switch UKWA Docker image builds to standard workflow

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-services#77]
We need to make sure all important Docker images are scanned for security issues as part of the GitHub Actions process, before the images are pushed to Docker Hub.

To do this, we can [reuse GitHub Actions workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows) across repositories, to ensure we build, scan and upload Docker Images consistently.

This is an example of a container that uses the shared workflow: https://github.com/ukwa/ukwa-warc-server/blob/master/.github/workflows/push-to-docker-hub.yml

The task here is to go through the stacks in this repository and update every referenced container build to re-use this shared workflow.  Every change should be proposed as a PR on each repository, and linked here for @anjackson to review.

**Comment by anjackson** [comment]
Note fragment is just

```
jobs:
  run_docker_build_workflow:
    uses: ukwa/ukwa-services/.github/workflows/push-to-docker-hub.yml@master
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
```

But the image name can be overridden if needed (see warc-server example)
